-- users
insert into budgeting_app_user (user_id, first_name, last_name) values (1, 'Red', 'Moisey');
insert into budgeting_app_user (user_id, first_name, last_name) values (2, 'Doti', 'Jerdein');
insert into budgeting_app_user (user_id, first_name, last_name) values (3, 'Prescott', 'Josupeit');
insert into budgeting_app_user (user_id, first_name, last_name) values (4, 'Sunshine', 'Lummasana');
insert into budgeting_app_user (user_id, first_name, last_name) values (5, 'Shanie', 'Puddle');
insert into budgeting_app_user (user_id, first_name, last_name) values (6, 'Estrellita', 'Mourbey');
insert into budgeting_app_user (user_id, first_name, last_name) values (7, 'Lisetta', 'Bielfeldt');
insert into budgeting_app_user (user_id, first_name, last_name) values (8, 'Ninetta', 'Engel');
insert into budgeting_app_user (user_id, first_name, last_name) values (9, 'Loraine', 'Mc Meekin');
insert into budgeting_app_user (user_id, first_name, last_name) values (10, 'Cherish', 'Hanes');
insert into budgeting_app_user (user_id, first_name, last_name) values (11, 'Francesco', 'Iglesia');
insert into budgeting_app_user (user_id, first_name, last_name) values (12, 'Sheri', 'Sawers');
insert into budgeting_app_user (user_id, first_name, last_name) values (13, 'Wit', 'Chastelain');
insert into budgeting_app_user (user_id, first_name, last_name) values (14, 'Ralf', 'Muff');
insert into budgeting_app_user (user_id, first_name, last_name) values (15, 'Bevvy', 'D''Alwis');
insert into budgeting_app_user (user_id, first_name, last_name) values (16, 'Nike', 'Lynett');
insert into budgeting_app_user (user_id, first_name, last_name) values (17, 'Barney', 'Coraini');
insert into budgeting_app_user (user_id, first_name, last_name) values (18, 'Carlos', 'Peron');
insert into budgeting_app_user (user_id, first_name, last_name) values (19, 'Eldin', 'Mant');
insert into budgeting_app_user (user_id, first_name, last_name) values (20, 'Craggie', 'Dubber');
insert into budgeting_app_user (user_id, first_name, last_name) values (21, 'Jaymee', 'Sam');
insert into budgeting_app_user (user_id, first_name, last_name) values (22, 'Torre', 'Frier');
insert into budgeting_app_user (user_id, first_name, last_name) values (23, 'Shir', 'Hallford');
insert into budgeting_app_user (user_id, first_name, last_name) values (24, 'Pebrook', 'Hubbold');
insert into budgeting_app_user (user_id, first_name, last_name) values (25, 'Lia', 'Flagg');

-- expenses
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (1, 'Transcat, Inc.', 'Capital Goods', 19.49, 1);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (2, 'OSI Systems, Inc.', 'Technology', 21.56, 2);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (3, 'HV Bancorp, Inc.', 'Finance', 85.56, 3);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (4, 'Blackrock Global', 'Food', 99.99, 4);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (5, 'Yulong Eco-Materials Limited', 'Capital Goods', 1.01, 5);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (6, 'Regions Financial Corporation', 'Finance', 72.25, 6);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (7, 'MGE Energy Inc.', 'Energy', 52.39, 7);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (8, 'BB&T Corporation', 'Food', 89.06, 8);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (9, 'GlaxoSmithKline PLC', 'Health Care', 96.51, 9);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (10, 'San Juan Basin Royalty Trust', 'Energy', 9.31, 10);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (11, 'China XD Plastics Company Limited', 'Capital Goods', 88.39, 11);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (12, 'Prosperity Bancshares, Inc.', 'Finance', 56.0, 12);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (13, 'Professional Diversity Network, Inc.', 'Technology', 60.4, 13);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (14, 'Walker & Dunlop, Inc.', 'Finance', 28.55, 14);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (15, 'Dermira, Inc.', 'Health Care', 108.81, 15);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (16, 'Potash Corporation of Saskatchewan Inc.', 'Basic Industries', 101.81, 16);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (17, 'Vornado Realty Trust', 'Food', 40.98, 17);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (18, 'Advaxis, Inc.', 'Health Care', 67.4, 18);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (19, 'SilverBow Resorces, Inc.', 'Energy', 110.13, 19);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (20, 'Approach Resources Inc.', 'Energy', 39.39, 20);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (21, 'Morgan Stanley', 'Food', 2.92, 21);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (22, 'Comtech Telecommunications Corp.', 'Technology', 103.14, 22);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (23, 'JELD-WEN Holding, Inc.', 'Basic Industries', 48.21, 23);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (24, 'State Bank Financial Corporation.', 'Finance', 62.19, 24);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (25, 'Cohen & Steers Reit and Preferred Income Fund Inc', 'Food', 43.06, 25);
