-- users
insert into budgeting_app_user (user_id, first_name, last_name) values (1, 'Red', 'Moisey');
insert into budgeting_app_user (user_id, first_name, last_name) values (2, 'Doti', 'Jerdein');
insert into budgeting_app_user (user_id, first_name, last_name) values (3, 'Prescott', 'Josupeit');
insert into budgeting_app_user (user_id, first_name, last_name) values (4, 'Sunshine', 'Lummasana');
insert into budgeting_app_user (user_id, first_name, last_name) values (5, 'Shanie', 'Puddle');
insert into budgeting_app_user (user_id, first_name, last_name) values (6, 'Estrellita', 'Mourbey');
insert into budgeting_app_user (user_id, first_name, last_name) values (7, 'Lisetta', 'Bielfeldt');
insert into budgeting_app_user (user_id, first_name, last_name) values (8, 'Ninetta', 'Engel');
insert into budgeting_app_user (user_id, first_name, last_name) values (9, 'Loraine', 'Mc Meekin');
insert into budgeting_app_user (user_id, first_name, last_name) values (10, 'Cherish', 'Hanes');
insert into budgeting_app_user (user_id, first_name, last_name) values (11, 'Francesco', 'Iglesia');
insert into budgeting_app_user (user_id, first_name, last_name) values (12, 'Sheri', 'Sawers');
insert into budgeting_app_user (user_id, first_name, last_name) values (13, 'Wit', 'Chastelain');
insert into budgeting_app_user (user_id, first_name, last_name) values (14, 'Ralf', 'Muff');
insert into budgeting_app_user (user_id, first_name, last_name) values (15, 'Bevvy', 'D''Alwis');
insert into budgeting_app_user (user_id, first_name, last_name) values (16, 'Nike', 'Lynett');
insert into budgeting_app_user (user_id, first_name, last_name) values (17, 'Barney', 'Coraini');
insert into budgeting_app_user (user_id, first_name, last_name) values (18, 'Carlos', 'Peron');
insert into budgeting_app_user (user_id, first_name, last_name) values (19, 'Eldin', 'Mant');
insert into budgeting_app_user (user_id, first_name, last_name) values (20, 'Craggie', 'Dubber');
insert into budgeting_app_user (user_id, first_name, last_name) values (21, 'Jaymee', 'Sam');
insert into budgeting_app_user (user_id, first_name, last_name) values (22, 'Torre', 'Frier');
insert into budgeting_app_user (user_id, first_name, last_name) values (23, 'Shir', 'Hallford');
insert into budgeting_app_user (user_id, first_name, last_name) values (24, 'Pebrook', 'Hubbold');
insert into budgeting_app_user (user_id, first_name, last_name) values (25, 'Lia', 'Flagg');

-- expenses
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (1, 'Gigashots', 'Food', 108.14, 1);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (2, 'Livepath', 'Technology', 69.64, 2);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (3, 'Oyope', 'Energy', 6.42, 3);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (4, 'Riffwire', 'Finance', 41.1, 4);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (5, 'Cogilith', 'Food', 111.54, 5);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (6, 'Dynabox', 'Consumer Services', 77.44, 6);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (7, 'Fivechat', 'Consumer Services', 93.61, 7);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (8, 'Realpoint', 'Health Care', 96.24, 8);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (9, 'Feedfish', 'Food', 1.01, 9);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (10, 'Zava', 'Finance', 52.32, 10);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (11, 'Zoomzone', 'Consumer Non-Durables', 105.85, 11);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (12, 'Trudoo', 'Finance', 18.2, 12);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (13, 'Jabbertype', 'Capital Goods', 64.23, 13);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (14, 'Dabshots', 'Health Care', 76.11, 14);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (15, 'Zoomcast', 'Health Care', 26.8, 15);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (16, 'Blogpad', 'Consumer Services', 35.04, 16);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (17, 'Skyvu', 'Energy', 53.07, 17);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (18, 'Kwilith', 'Food', 50.67, 18);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (19, 'Fivechat', 'Consumer Services', 41.09, 19);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (20, 'Eazzy', 'Finance', 93.63, 20);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (21, 'Cogilith', 'Public Utilities', 63.4, 21);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (22, 'Linktype', 'Consumer Services', 90.39, 22);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (23, 'Meevee', 'Transportation', 1.41, 23);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (24, 'Fatz', 'Public Utilities', 87.92, 24);
insert into budgeting_app_expense (expense_id, merchant, category, cost, user_id) values (25, 'Dazzlesphere', 'Consumer Durables', 51.65, 25);
